# Dependencies
markdown:         redcarpet
highlighter:      pygments
#highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nikolay Mishin
#tagline:          None
url:              http://mishin.github.io
paginate:         5
baseurl:          /
author:
  name:           Nikolay Mishin
  url:            http://mishin.github.io
  email:          none@none.com
  
#excerpt_separator: <!--more-->
excerpt_separator: <span class="more"></span>

exclude:          [_ignore]

# Don't forget to add these to sitemap.xml
pages_list:
  ABOUT:          '/about'
  ARCHIVE:        '/archive'
  FEED:           '/atom.xml'
  
# Custom vars
version:          1.0.0
github:           
  repo:           https://github.com/mishin
  
comments:
  provider:       disqus
  disqus:
    short_name:   mishin

timezone:         Europe/Moscow

# Gems
gems: [jekyll-paginate]
paginate: 3